### ISSUE TITLE
java.net.URISyntaxException when I'm cloning repo from local gitlab

### ISSUE THREAD

**Issue by surik** [someteam/acha#24]
I was trying to clone ```git@gitlab.eltex.loc:ecss/teleconference.git``` and got exception:
```
Cannot addgit@gitlab.eltex.loc:ecss/teleconference.git: java.net.URISyntaxException: Illegal character in scheme name at index 3: git@gitlab.eltex.loc:ecss/teleconference.git
```

```
$ java -version
java version "1.7.0_75"
OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-1~trusty1)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)
```

**Comment by avasenin** [comment]
Use current master instead
18.03.2015 11:19 пользователь "Yury Gargay" <notifications@github.com>
написал:

**Comment by surik** [comment]
Ok, thanks. It works.

**Comment by avasenin** [comment]
i've released 0.2.5 version

**Comment by leoschweizer** [comment]
@avasenin I'm experiencing the exact same issue when running the version provided through https://github.com/someteam/acha/releases/download/0.2.5/acha-uber-0.2.5.jar - also, the version number on the website is displayed as `0.2.4`!

So either the published jar is not really version `0.2.5`, or the issue is not fixed. I've tried to build from source for some time now to check if it is working on master, but I can't even get Leiningen to run properly on my windows machine here :disappointed:

**Comment by avasenin** [comment]
I'm traveling right now. I will check this on the next week.
